title: Treat flip cards
hero_image: images/banner.png
description: Create a set of interactive cards that tell people about sweet treats from around the world.
pdf: resources/rpfi-flip-your-card.pdf
meta_title: CSS tutorial | Learn web development | Treat flip cards
meta_description: In this CSS tutorial you will learn web development with the Raspberry Pi Foundation. Use CSS animations to create interactive cards that flip over.
version: 4
listed: true
copyedit: true
last_tested: "2026-03-02"
steps:
  - title: You will make
  - title: Build Your First Card
  - title: Make the Card Flip
    completion:
      - engaged
  - title: Style the Card Faces
  - title: Import a Display Font
    completion:
      - internal
  - title: Polish the Front Face
    completion:
      - external
  - title: "Challenge: Create Your Own Palette"
    challenge: true
